# Swarm Simulator for Outer Space

This swarm simulator will explore different swarm algorithms for an application in outer space. This approach will divide a plot into grid squares, which can then be analysed to determine and control the behaviour of each individual agent in the swarm.

In [1]:
#imports
import sympy as sym
import plotly as py
import plotly.tools as tls
from plotly import graph_objs as go
import plotly.express as px
from plotly.subplots import make_subplots
from IPython.display import Image

import dash
from dash.dependencies import Output, Input
import dash_core_components as dcc
import dash_html_components as html

import numpy as np
import pandas as pd
import ipywidgets as widgets
import time
import math

from scipy import special
from plotly.offline import download_plotlyjs, init_notebook_mode, plot, iplot
from collections import deque
from scipy.spatial.distance import cdist, pdist, euclidean
from sympy import sin, cos, symbols, lambdify

from robot import Robot
from dust_devil import DustDevil
from live_functions import initialise,random_position, grid_center,positions,bounce,magnitude,unit,division_check,physics_walk,dust_check,update_timestep,cluster_function,G_transition,dist,random_walk,dust,trajectory_dust,update_dust,load_positions,pre_initialise

import random
import datetime
import os
import math
import sys

import Processing_Functions_BP


import dash
from dash.dependencies import Output, Input
import dash_core_components as dcc
import dash_html_components as html

import json
import pickle

from ast import literal_eval

app = dash.Dash(__name__)

In [2]:
#Plotly offline mode
init_notebook_mode(connected=True)

In [2]:
def directory_load(path):
    store_robots = np.load(path + "Robots.npy")
    with open(path + "dust.txt", "r") as f:
        store_dust = json.load(f)


    constants = pd.read_excel(path + "Constants.xlsx", index_col=0)
    min_neighbours = np.load(path + 'Minimum Distance to Neighbours.npy')
    cluster_average = np.load(path + 'Cluster Average.npy')
    total_collision = np.load(path + 'Measurement Events Count.npy')
    total_detection = np.load(path + 'Number of Dust Devils Detected.npy')
    total_dust = np.load(path + 'Number of Dust Devils Generated.npy')
    #setting the start paths for the graphs and the tables
    return constants,min_neighbours,cluster_average,total_collision,total_detection,total_dust
    

In [4]:
import numpy as np
word = "Robots"
word_run = "Run_"
array = [10]#,20,30,40,50,60,70,80,90,100]
runs = 1
directory = "../Experiments/Area Coverage 2.2. Testing Optimizer/"
image = directory + "Images/"

final = []

time = 5000
for i in array:
    outer_path = directory + str(i) + " " + word + "/"
    for j in range(runs):

        path = outer_path + word_run + str(j) + "/"
        print(np.load(path+"Area_Coverage_Results.npy"))
        

[[190.           9.        ]
 [200.           9.        ]
 [200.           9.        ]
 [205.           9.        ]
 [205.           9.        ]
 [205.55555556   9.        ]
 [210.           9.        ]
 [211.11111111   9.        ]
 [216.66666667   9.        ]
 [222.22222222   9.        ]
 [227.77777778   9.        ]
 [233.33333333   9.        ]
 [238.88888889   9.        ]
 [244.44444444   9.        ]
 [250.           9.        ]]


In [12]:
word = "Robots"
word_run = "Run_"
array = [10,20,30,40,50,60,70,80,90,100]
runs = 10
directory = "Blue_Pebble/Fixed/"
image = directory + "Images/"
time = 86400
final = []
frequency = 1
for i in array:
    outer_path = directory + str(i) + " " + word + "/"
    for j in range(runs):

        path = outer_path + word_run + str(j) + "/"
        code = str(i) + " " + word + " "
        store_robots = np.load(path + "Robots.npy")
        with open(path + "dust.txt", "r") as f:
            store_dust = json.load(f)
        print(len(list(store_robots)))
        constants = pd.read_excel(path + "Constants.xlsx", index_col=0)
        min_neighbours = np.load(path + 'Minimum Distance to Neighbours.npy')
        cluster_average = np.load(path + 'Cluster Average.npy')
        total_collision = np.load(path + 'Measurement Events Count.npy')
        total_detection = np.load(path + 'Number of Dust Devils Detected.npy')
        total_dust = np.load(path + 'Number of Dust Devils Generated.npy')
        #setting the start paths for the graphs and the tables
       #setting the start paths for the graphs and the tables
        graph_start_path = image + code + "- Graph_Beginning.png"
        table_start_path = image +code + "- Table_Beginning.png"

        #using the processing functions to create plotly graphs and tables for the figures in the first timestep
        graph_start = Processing_Functions_Tracking.graph_figure(store_robots,0,frequency,code)
        graph_start.write_image(graph_start_path)
        table_start = Processing_Functions_Tracking.table_figure_area(store_robots,0,frequency,constants,min_neighbours,cluster_average)
        table_start.write_image(table_start_path)

        #combining the tables and the graphs using pillow
        Processing_Functions_Tracking.combine(graph_start_path,table_start_path)
        #setting the end paths for the graphs and the tables
        graph_end_path = image + code + "- Graph_End.png"
        table_end_path =image + code + "- Table_End.png"

        #using the processing functions to create plotly graphs and tables for the figures in the last timestep
        graph_end = Processing_Functions_Tracking.graph_figure(store_robots,time-1,frequency,code)
        graph_end.write_image(image + code + "- Graph_End.png")
        table_end = Processing_Functions_Tracking.table_figure_area(store_robots,time-1,frequency,constants,min_neighbours,cluster_average)
        table_end.write_image(image + code + "- Table_End.png")

        #using the processing functions to create plotly graphs and tables for the figures in the last timestep
        graph_end_types = Processing_Functions_Tracking.graph_types(x_0,y_0,x_1,y_1,500,10,"Deployed Swarm Formation ", " <b>Timestep = " + str(time) + " s<br>R = " + str(round(R,2)) + "</b> <br> ")
        graph_end_types.write_image(image + code + "- Graph_End_Types.png")


        #using the processing functions to create plotly graphs and tables for the figures in the last timestep
        graph_end_area_coverage = Processing_Functions_Tracking.graph_area_coverage(x_0,y_0,x_1,y_1,500,10, "Area Coverage Over a Grid for a Deployed Swarm Formation"," <b>Timestep = " + str(time) + " s<br>R = " + str(round(R,2)) + "<br>Area Coverage = " + str(current_grid_metric) + "%</b><br> ")
        graph_end_area_coverage.write_image(image + code + "- Graph_End_Area_Coverage.png")
        #table_end_types = Processing_Functions_Tracking.table_figure(store_robots,time-1,frequency,constants,min_neighbours,cluster_average,total_collision,total_detection,total_dust)
        #table_end.write_image(image + "/" + code + "- Table_Types_End.png")

        #combining the tables and the graphs using pillow
        Processing_Functions_Tracking.combine(graph_end_path,table_end_path)

        #plotting performance of the average of minimum neighbouring distance metric
        performance = Processing_Functions_Tracking.performance_graph(min_neighbours,np.linspace(0,len(min_neighbours),len(min_neighbours)*frequency,endpoint = False),frequency,code,"Time (s)","Minimum Average Neighbour Distance (m)")
        performance.write_image(image + code + "- Minimum Neighbour Average.png")

        #plotting performance of the dust devil measurement metric
        performance_intercept = Processing_Functions_Tracking.performance_graph(total_collision,np.linspace(0,len(total_collision),len(total_collision)*frequency,endpoint = False),frequency,code,"Time (s)","Count of Measurement Events")
        performance_intercept.write_image(image + "/" + code + "- Intercept Performance.png")

        #plotting performance of the cluster average of the swarm
        cluster = Processing_Functions_Tracking.performance_graph(cluster_average,np.linspace(0,len(cluster_average),len(cluster_average)*frequency,endpoint = False),frequency,code,"Time (s)","Average Cluster Size")
        cluster.write_image(image + code +  "- Average Cluster Size.png")

        final_np = np.load(path+'Final Dust Devil Count.npy')
        final.append([list(final_np[-1])])
        print(final)
        print(total_dust)
        print((total_dust[-1]))
    print(final)
    np.save(directory + "Performance vs Robot Number.npy",final)

10
2
10 Robots 
10 Robots 
10 Robots 
[[[10, 27]]]
[  0   0   0 ... 420 420 420]
420
20
2
20 Robots 
20 Robots 
20 Robots 
[[[10, 27]], [[20, 46]]]
[  0   0   0 ... 420 420 420]
420
30
2
30 Robots 
30 Robots 
30 Robots 
[[[10, 27]], [[20, 46]], [[30, 60]]]
[  0   0   0 ... 421 421 421]
421
40
2
40 Robots 
40 Robots 
40 Robots 
[[[10, 27]], [[20, 46]], [[30, 60]], [[40, 91]]]
[  0   0   0 ... 420 421 421]
421
50
2
50 Robots 
50 Robots 
50 Robots 
[[[10, 27]], [[20, 46]], [[30, 60]], [[40, 91]], [[50, 94]]]
[  0   0   0 ... 422 422 422]
422
60
2
60 Robots 
60 Robots 
60 Robots 
[[[10, 27]], [[20, 46]], [[30, 60]], [[40, 91]], [[50, 94]], [[60, 108]]]
[  0   0   0 ... 421 421 421]
421
70
2
70 Robots 
70 Robots 
70 Robots 
[[[10, 27]], [[20, 46]], [[30, 60]], [[40, 91]], [[50, 94]], [[60, 108]], [[70, 118]]]
[  0   0   0 ... 422 422 422]
422
80
2
80 Robots 
80 Robots 
80 Robots 
[[[10, 27]], [[20, 46]], [[30, 60]], [[40, 91]], [[50, 94]], [[60, 108]], [[70, 118]], [[80, 129]]]
[  0   0   0

In [ ]:
performance_metric_np = np.array(final)
performance_metric = performance_metric_np[:,0]
print(performance_metric[:,1])
performance_overall = Processing_Functions_BP.performance_graph(performance_metric[:,1],performance_metric[:,0],1,"","Number of Robots","Number of Dust Devils Detected")
performance_overall.write_image(directory + "Detection Performance vs Robot Number.png")

In [ ]:
directory1 = "Blue_Pebble/Robot Array/10 Robots%20/"
directory2 = "Blue_Pebble/Robot Array/30 Robots%20/"
with open(directory1 + "dust.txt", "r") as f:
        store_dust1 = json.load(f)
with open(directory2 + "dust.txt", "r") as f:
        store_dust2 = json.load(f)
print(store_dust1[10000])
print(store_dust2[10000])

In [ ]:
-156.26497956057256,-156.5109418975476 73.9590318896967